### ISSUE TITLE
KeyError: 'has_project' (Windows 10)

### ISSUE THREAD

**Issue by ksere** [gwenzek/SublimeSetWindowTitle#7]
Hi, getting this with 1.3.2 ( Sublime 3.0.3170 on Windows 10 ). 

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 611, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 118, in on_activated_async
    self.run(view)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 136, in run
    new_title = get_new_title(view, project, settings)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 239, in get_new_title
    new_title = template.format(path=path, project=project)
KeyError: 'has_project'
```

Same error when using the default config file included in the release.

Cheers

**Comment by gwenzek** [comment]
Hi, thanks for reporting.
I think I have a fix for this somewhere but that I haven't  pushed it.
I'm gonna look into this this week.

**Comment by gwenzek** [comment]
I think what triggered the bug is the handling of {project} outside of a project when {has_project_false} is empty.

Can you try to set "has_project_false" settings to "()" or something else to see if the bug still happens ?
If that fix the bug then my last commit should work, please try it if you can, otherwise I'll just publish  a new release.

**Comment by gwenzek** [comment]
I created a new release with the fix, tell me if the issue persists.

**Comment by ksere** [comment]
Hi,

Sorry I hadn't got around to testing with "has_project_false" settings to "()".

I just tested with 1.3.3 and getting this:

```
reloading plugin SetWindowTitle.set_window_title
reloading settings Packages/SetWindowTitle/set_window_title.sublime-settings
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 611, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 118, in on_activated_async
    self.run(view)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 137, in run
    self.rename_window(view.window(), official_title, new_title, settings)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 164, in rename_window
    self.rename_window_windows(window, official_title, new_title)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 203, in rename_window_windows
    for w in Window.list_all():
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 69, in list_all
    return [cls(handle) for handle in handles]
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 69, in <listcomp>
    return [cls(handle) for handle in handles]
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 36, in __init__
    self.init_user32()
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 75, in init_user32
    cls.u.EnumWindows.restype = cls.c.c_bool
AttributeError: type object 'Window' has no attribute 'c'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 233, in synthesize_on_activated_async
    el.on_activated_async(v)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 118, in on_activated_async
    self.run(view)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 137, in run
    self.rename_window(view.window(), official_title, new_title, settings)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 164, in rename_window
    self.rename_window_windows(window, official_title, new_title)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 203, in rename_window_windows
    for w in Window.list_all():
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 69, in list_all
    return [cls(handle) for handle in handles]
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 69, in <listcomp>
    return [cls(handle) for handle in handles]
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 36, in __init__
    self.init_user32()
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 75, in init_user32
    cls.u.EnumWindows.restype = cls.c.c_bool
AttributeError: type object 'Window' has no attribute 'c'
```

And also getting the same error when setting "has_project_false" settings to "()".

No hurry for me, I will install manually the last working version.
Thanks for looking into it and let me know if there is anything else I can help you test.

**Comment by gwenzek** [comment]
Ok this seems to be specific to Windows and unrelated.
I'm opening #8 to track this.
