### ISSUE TITLE
AttributeError: type object 'Window' has no attribute 'c'

### ISSUE THREAD

**Issue by gwenzek** [gwenzek/SublimeSetWindowTitle#8]
AttributError happening on Windows:
Initially reported in #7 by @ksere but this seems to be a totally unrelated bug, so reopening here.

@cjdoris can you have a look please ? (Don't have an easy access to a Windows machine)
I don't understand how it worked in the first place.
For me the "cls.c" in the `init_user32` mthod should be replaced by `ctypes`.
WDYT ?

https://github.com/gwenzek/SublimeSetWindowTitle/commit/8932b26f9475c6d329857b751ece71191a462903#diff-a7908ba95124deb7948b618398904c6eR61

@ksere Could you tell me which was the last version working for you  ? I think this was introduced in 1.3.0

```
reloading plugin SetWindowTitle.set_window_title
reloading settings Packages/SetWindowTitle/set_window_title.sublime-settings
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 611, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 118, in on_activated_async
    self.run(view)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 137, in run
    self.rename_window(view.window(), official_title, new_title, settings)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 164, in rename_window
    self.rename_window_windows(window, official_title, new_title)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 203, in rename_window_windows
    for w in Window.list_all():
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 69, in list_all
    return [cls(handle) for handle in handles]
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 69, in <listcomp>
    return [cls(handle) for handle in handles]
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 36, in __init__
    self.init_user32()
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 75, in init_user32
    cls.u.EnumWindows.restype = cls.c.c_bool
AttributeError: type object 'Window' has no attribute 'c'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 233, in synthesize_on_activated_async
    el.on_activated_async(v)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 118, in on_activated_async
    self.run(view)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 137, in run
    self.rename_window(view.window(), official_title, new_title, settings)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 164, in rename_window
    self.rename_window_windows(window, official_title, new_title)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 203, in rename_window_windows
    for w in Window.list_all():
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 69, in list_all
    return [cls(handle) for handle in handles]
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 69, in <listcomp>
    return [cls(handle) for handle in handles]
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 36, in __init__
    self.init_user32()
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 75, in init_user32
    cls.u.EnumWindows.restype = cls.c.c_bool
AttributeError: type object 'Window' has no attribute 'c'
```

**Comment by gwenzek** [comment]
Ok I think I broke this in [f0354](https://github.com/gwenzek/SublimeSetWindowTitle/commit/f03547f9c2d5f4c3f5a012b8007ba91bd51e8f4b#diff-a7908ba95124deb7948b618398904c6eR23)
when moving the `import ctypes as c` statement up.

I don't think importing at the class level was a good thing to do in the first place, so I've refactored this in: fd00e9eba1e64702473d19c9815328fb34970135

Can someone tests that it does work on Windows ?

**Comment by gwenzek** [comment]
Releasing 1.3.4 to try to fix this (I haven't tested on Windows so ...)

**Comment by ksere** [comment]
Tested on 1.3.4 and getting this:

```
reloading plugin SetWindowTitle.set_window_title
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 611, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 118, in on_activated_async
    self.run(view)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 137, in run
    self.rename_window(view.window(), official_title, new_title, settings)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 164, in rename_window
    self.rename_window_windows(window, official_title, new_title)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 203, in rename_window_windows
    for w in Window.list_all():
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 68, in list_all
    cls.user32.EnumWindows(WNDENUMPROC(cb), None)
AttributeError: 'NoneType' object has no attribute 'EnumWindows'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 233, in synthesize_on_activated_async
    el.on_activated_async(v)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 118, in on_activated_async
    self.run(view)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 137, in run
    self.rename_window(view.window(), official_title, new_title, settings)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 164, in rename_window
    self.rename_window_windows(window, official_title, new_title)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 203, in rename_window_windows
    for w in Window.list_all():
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 68, in list_all
    cls.user32.EnumWindows(WNDENUMPROC(cb), None)
AttributeError: 'NoneType' object has no attribute 'EnumWindows'
reloading settings Packages/User/Preferences.sublime-settings
```

Same issue: [#9](https://github.com/gwenzek/SublimeSetWindowTitle/issues/9)

**Comment by gwenzek** [comment]
Can you try with 6e47629c8e6a497977261f14e65a4929b8730f5e ?
As I said I don't have Windows, and Travis only test on Linux, so I'm just blindly moving code around here.
If someone could test and fix the initialization of user32 that'd be nice!

**Comment by ksere** [comment]
Nope, it throws:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 611, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Packages\User\set_window_title.py", line 115, in on_activated_async
    self.run(view)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Packages\User\set_window_title.py", line 134, in run
    self.rename_window(view.window(), official_title, new_title, settings)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Packages\User\set_window_title.py", line 161, in rename_window
    self.rename_window_windows(window, official_title, new_title)
  File "C:\Users\kse\AppData\Roaming\Sublime Text 3\Packages\User\set_window_title.py", line 200, in rename_window_windows
    for w in list_all_windows():
TypeError: list_all_windows() missing 1 required positional argument: 'cls'
```

Keep in mind, as i 've said previously, [1.3.1](https://github.com/gwenzek/SublimeSetWindowTitle/blob/1.3.1/set_window_title.py) was working for me and i am using that version. I wish i could help but i have zero experience with Python.

Cheers.

**Comment by gwenzek** [comment]
not an efficient way of coding but we are converging: f4d4229 should fix that.
I'm aware 1.3.1 was working but the code was a bit convoluted, I tried to make it more readable, now it seems easier to fix it rather than rollback the previous versions that also fixed some bugs.

**Comment by ksere** [comment]
Looks like its working fine!

**Comment by cjdoris** [comment]
The latest commit works fine for me.

**Comment by gwenzek** [comment]
Great thanks for confirming. I cut a release.
Sorry again for the mess, I promise to not touch working code anymore ^^
