### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'EnumWindows' (v1.3.4 & Windows 10)

### ISSUE THREAD

**Issue by asimen1** [gwenzek/SublimeSetWindowTitle#9]
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 611, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\Asaf\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 118, in on_activated_async
    self.run(view)
  File "C:\Users\Asaf\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 137, in run
    self.rename_window(view.window(), official_title, new_title, settings)
  File "C:\Users\Asaf\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 164, in rename_window
    self.rename_window_windows(window, official_title, new_title)
  File "C:\Users\Asaf\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 203, in rename_window_windows
    for w in Window.list_all():
  File "C:\Users\Asaf\AppData\Roaming\Sublime Text 3\Installed Packages\SetWindowTitle.sublime-package\set_window_title.py", line 68, in list_all
    cls.user32.EnumWindows(WNDENUMPROC(cb), None)
AttributeError: 'NoneType' object has no attribute 'EnumWindows'

**Comment by gwenzek** [comment]
this a consequence at my blind attempt at fixing #8.
Please follow up on the other bug.
